version: '3'
services:
  data_warehouse_hotel_db:
    image: postgres:latest
    container_name: data_warehouse_hotel_db
    restart: always
    environment:
      - POSTGRES_DB=hotel_analysis_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cobapassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5434:5432 